version: "3.8"

services:
  migratio:
    container_name: migratio
    build:
      dockerfile: Dockerfile.development
    stdin_open: true
    volumes:
      - ./:/app

  postgres:
    container_name: migratio_postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=""
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
